### ISSUE TITLE
Final Capstone Kanban Board

### ISSUE THREAD

**Issue by Felipe-Perez-Ferraro** [Felipe-Perez-Ferraro/final_capstone_front#10]
### Project Colaborators
- @ulises2607 
- @hajnaloltyan 
- @Felipe-Perez-Ferraro 

### In this issue we
- Create tasks 
- Asign tasks

Thank you for reading this, any doubt please ask it.

### Project Links
[Kanban Board](https://github.com/users/Felipe-Perez-Ferraro/projects/2)
[Final Capstone Project FRONT](https://github.com/Felipe-Perez-Ferraro/final_capstone_front)
[Final Capstone Project BACK](https://github.com/Felipe-Perez-Ferraro/final_capstone_back)

### Kanban Board
![kanban](https://github.com/Felipe-Perez-Ferraro/final_capstone_front/assets/102243581/42428055-78ec-47fb-9239-ab9b20402975)

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have descriptions✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

There are 2 tasks with the same description:

![image](https://github.com/Felipe-Perez-Ferraro/final_capstone_front/assets/57421823/c84ca27f-7cda-4316-8dc6-94760fefdaab)

![image](https://github.com/Felipe-Perez-Ferraro/final_capstone_front/assets/57421823/83c47dfe-6482-492e-a170-3676b9074742)

Kindly, make sure the description is not exactly the same for these 2 different tasks.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Descriptions are now consistent✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
